#!/bin/bash

# This script is deployed at /etc/init.d/ and it is used to manage the 
# CELAR Orchestrator.

[ -z "$CELAR_ORCHESTRATOR_HOME" ] && CELAR_ORCHESTRATOR_HOME="/opt/celar/celar-orchestrator"

LIB_DIR=$CELAR_ORCHESTRATOR_HOME/lib
CONF_DIR=$CELAR_ORCHESTRATOR_HOME/conf

MAIN_CLASS=gr.ntua.cslab.orchestrator.Main

CLASSPATH=$CONF_DIR
CLASSPATH=$CLASSPATH:$(echo $LIB_DIR/*.jar | tr ' ' ':')
CLASSPATH=$CLASSPATH:$CELAR_ORCHESTRATOR_HOME/celar-orchestrator.jar
PIDFILE=/tmp/celar-orchestrator.pid

start() {
	java -Dname=celar-orchestrator -cp $CLASSPATH  $MAIN_CLASS &
	echo $! > $PIDFILE;
}

stop() {
	PID=$(cat $PIDFILE)
	kill -TERM $PID
	rm -f $PIDFILE
}

status() {
	if [ -f $PIDFILE ]; then
		PID=$(cat $PIDFILE)
		echo "CELAR Orchestrator running ($PID)"
	else
		echo "CELAR Orchestrator not running"
	fi
}


case $1 in
	start)
		start;
		;;
	stop)
		stop;
		;;
	restart)
		stop && start;
		;;
	status)
		status;
		;;
	*)
		echo "$0 {start|stop|status|restart}"
		;;
esac

