#!/bin/bash

[ "$CLIENT_HOME" == "" ] && CLIENT_HOME="/Users/nikospapailiou/Documents/workspace/app-orchestrator/orchestrator-client/"

LIB_DIR=$CLIENT_HOME/lib
CONF_DIR=$CLIENT_HOME/conf
MAIN_CLASS="gr.ntua.cslab.orchestrator.client.cli.CLIClient"

CLASSPATH=$CONF_DIR
CLASSPATH=$CLASSPATH:$(echo $LIB_DIR/*.jar | tr ' ' ':')
CLASSPATH=$CLASSPATH:$CLIENT_HOME/orchestrator-client-0.1-SNAPSHOT.jar


java -cp $CLASSPATH $MAIN_CLASS $@
