#!/bin/bash

CLIENT_HOME="/Users/nikospapailiou/Documents/workspace/app-orchestrator/orchestrator-client/"
JAR_FILE_LOCATION="${CLIENT_HOME}target/orchestrator-client-0.1-SNAPSHOT.jar"
CLASSPATH="${CLIENT_HOME}target/lib/*"
MAIN_CLASS="gr.ntua.cslab.orchestrator.client.cli.CLIClient"

java -cp "${CLASSPATH}:${JAR_FILE_LOCATION}" ${MAIN_CLASS} $@
